jobs:
- job: BuildMacOS
  pool:
    vmImage: 'macOS 10.14'

  timeoutInMinutes: 360

  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/macos_script
    name: main
    displayName: 'Build and test'
- job: BuildLinux
  pool:
    vmImage: 'ubuntu-18.04'

  timeoutInMinutes: 360

  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/linux_script
    name: main
    displayName: 'Build and test'
- job: BuildWindows
  pool:
    vmImage: 'windows-2019'

  timeoutInMinutes: 360

  steps:
  - script: |
      git clone https://github.com/lazka/msys2-ci-base.git %CD:~0,2%\msys64
      %CD:~0,2%\msys64\usr\bin\rm -rf %CD:~0,2%\msys64\.git
      set PATH=%CD:~0,2%\msys64\usr\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem
      %CD:~0,2%\msys64\usr\bin\pacman --noconfirm -Syyuu
    displayName: Install and Update MSYS2
  - task: DownloadSecureFile@1
    inputs:
      secureFile: s3cfg
  - script: ci/azure/windows_script.bat
    name: main
    displayName: 'Build and test'
- job: OnMasterSuccess
  dependsOn:
  - BuildMacOS
  - BuildLinux
  - BuildWindows
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  strategy:
    maxParallel: 1
  pool:
    vmImage: 'ubuntu-18.04'
  variables:
    version: $[ dependencies.BuildLinux.outputs['main.version'] ]
  steps:
  - task: DownloadSecureFile@1
    inputs:
      secureFile: oauth_token
  - script: ci/azure/on_master_success
    displayName: 'master branch success hook'
